# Demo Binary Classification Tuner for MSSP/Other projects built in Shiny


library(shiny)

fluidPage(
  mainPanel(
    numericInput("age", "Age", value = 70, min = 1, max = 110, step = 1 ),
    numericInput("num_meds", "Number of Medications", value = 0, min = 0, max = 50, step =1),
    checkboxGroupInput("covariates", "Select which Conditions apply", c("Inpatient",
                                                                        "Male",
                                                                      "CHF",
                                                                      "FluidsLytes",
                                                                      "Paralysis",
                                                                      "PHTN",
                                                                      "Valvular",
                                                                      "Anemia",
                                                                      "NeuroOther",
                                                                      "BloodLoss",
                                                                      "HTN",
                                                                      "Renal",
                                                                      "WeightLoss",
                                                                      "Coagulopathy",
                                                                      "Pulmonary",
                                                                      "Psychoses",
                                                                      "DMcx",
                                                                      "Mets",
                                                                      "Hypothyroid",
                                                                      "Liver",
                                                                      "Depression",
                                                                      "Obesity",
                                                                      "Tumor",
                                                                      "PVD",
                                                                      "DM",
                                                                      "Alcohol",
                                                                      "Drugs",
                                                                      "former Smoking",
                                                                      "Other organ transplantation",
                                                                      "Insertion, revision, replacement, removal of cardiac pacemaker or cardioverter/defibrillator",
                                                                      "Kidney transplant",
                                                                      "Coronary artery bypass graft (CABG)",
                                                                      "Transurethral resection of prostate (TURP)",
                                                                      "Other non-OR therapeutic cardiovascular procedures",
                                                                      "Varicose vein stripping, lower limb",
                                                                      "Other OR therapeutic procedures of urinary tract",
                                                                      "Incision and drainage, skin and subcutaneous tissue",
                                                                      "Other OR heart procedures",
                                                                      "Procedures on the urethra",
                                                                      "Tracheostomy, temporary and permanent",
                                                                      "Other OR procedures on vessels of head and neck",
                                                                      "Heart valve procedures",
                                                                      "Ileostomy and other enterostomy",
                                                                      "Exploratory laparotomy",
                                                                      "Suture of skin and subcutaneous tissue",
                                                                      "Aortic resection, replacement or anastomosis",
                                                                      "Other OR therapeutic procedures, male genital",
                                                                      "Peripheral vascular bypass",
                                                                      "Endoscopy and endoscopic biopsy of the urinary tract",
                                                                      "Hysterectomy, abdominal and vaginal",
                                                                      "Treatment, fracture or dislocation of hip and femur",
                                                                      "Lobectomy or pneumonectomy",
                                                                      "Transurethral excision, drainage, or removal urinary obstruction",
                                                                      "Other OR therapeutic procedures, female organs",
                                                                      "Other OR upper GI therapeutic procedures",
                                                                      "Other vascular bypass and shunt, not heart",
                                                                      "Other hernia repair",
                                                                      "Small bowel resection",
                                                                      "Colostomy, temporary and permanent",
                                                                      "Other OR therapeutic procedures on respiratory system",
                                                                      "Colorectal resection",
                                                                      "Nephrectomy, partial or complete",
                                                                      "Other OR therapeutic nervous system procedures",
                                                                      "Other OR lower GI therapeutic procedures",
                                                                      "Excision, lysis peritoneal adhesions",
                                                                      "Genitourinary incontinence procedures",
                                                                      "Embolectomy and endarterectomy of lower limbs",
                                                                      "Creation, revision and removal of arteriovenous fistula or vessel-to-vessel cannula for dialysis",
                                                                      "Cholecystectomy and common duct exploration",
                                                                      "Skin graft",
                                                                      "Laminectomy, excision intervertebral disc",
                                                                      "Oophorectomy, unilateral and bilateral",
                                                                      "Hip replacement, total and partial",
                                                                      "Other non-OR therapeutic procedures on skin and breast",
                                                                      "Cesarean section",
                                                                      "Other extraocular muscle and orbit therapeutic procedures",
                                                                      "Arthroplasty knee",
                                                                      "Lumpectomy, quadrantectomy of breast",
                                                                      "Other intraocular therapeutic procedures",
                                                                      "PHONE_SCREEN",
                                                                      "Excision of skin lesion",
                                                                      "Decompression peripheral nerve",
                                                                      "Bunionectomy or repair of toe deformities",
                                                                      "Other therapeutic procedures on muscles and tendons",
                                                                      "Repair of retinal tear, detachment",
                                                                      "Arthroplasty other than hip or knee",
                                                                      "Other therapeutic procedures on eyelids, conjunctiva, cornea",
                                                                      "Corneal transplant",
                                                                      "Glaucoma procedures",
                                                                      "Lens and cataract procedures",
                                                                      "Anticoagulants",
                                                                      "Anesthetics",
                                                                      "Antibiotics",
                                                                      "Cardiac medications",
                                                                      "Analgesics")),
    br(),
    verbatimTextOutput('risk_score')
)

)
                



